# Generated by Django 3.2.7 on 2021-09-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_to_unit_prices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unit_prices',
            new_name='unit_price',
        ),
    ]
